version: "3.8"
services:
  dev:
    container_name: yapo_test_dev_frontend
    image: yapo-test-dev-front:1.0.0
    build: .
    command: sh -c "npm start"
    ports:
      - 4200:4200
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
    restart: unless-stopped
volumes:
  node_modules:
