version: '3.8'

services:
  dev:
    container_name: yapo_test_dev
    image: yapo-test-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: yarn start:dev
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  prod:
    container_name: yapo_test_prod
    image: yapo-test-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: yarn start:prod
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  nesjs-network:
